# Turn on the built-in CORS filter
quarkus.http.cors.enabled=true

# Allow any origin during local development using a wildcard regex
%dev.quarkus.http.cors.origins=/.*/
%dev.quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
%dev.quarkus.http.cors.headers=accept,authorization,content-type,origin,x-requested-with
quarkus.http.host=0.0.0.0